### ISSUE TITLE
Make gp.org MU

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#43]
# Tasks for Mervin
- [x] 1. Make `gatherpress.org` MU
- [x] 2. Add mike as a user
- [x] 3. Link `gatherpress.org` to GitRepo
- [x] 4. Add mike as SSH user on Spin2 (Mervin's)

---

# Setup MU
- Subdirectory is fine ... let's not worry about subdomain for now

**Comment by MervinHernandez** [comment]
Still pending

**Comment by MervinHernandez** [comment]
✅ done done
